import React, { useState } from 'react';
import { ArrowLeft, Layers, Shuffle, RefreshCw, Download, Loader2 } from 'lucide-react';

interface Flashcard {
  front: string;
  back: string;
}

interface FlashcardViewProps {
  flashcards: Flashcard[];
  onBack: () => void;
}

const FlashcardView = ({ flashcards: initialFlashcards, onBack }: FlashcardViewProps) => {
  const [flashcards, setFlashcards] = useState(initialFlashcards);
  const [flippedIndices, setFlippedIndices] = useState<number[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  
  const handleCardClick = (index: number) => {
    setFlippedIndices(prev => 
      prev.includes(index) ? prev.filter(i => i !== index) : [...prev, index]
    );
  };

  const handleShuffle = () => {
    const shuffled = [...flashcards].sort(() => Math.random() - 0.5);
    setFlashcards(shuffled);
    setFlippedIndices([]); 
  };

  // --- THE FIXED DOWNLOAD FUNCTION ---
  const handleDownloadPDF = async () => {
    setIsDownloading(true);

    try {
      const html2pdf = (await import('html2pdf.js')).default;
      
      // 1. Create a temporary container for the PDF content
      const element = document.createElement('div');
      
      // 2. Build the HTML string using the flashcards data
      // This creates a simple, clean, line-by-line list
      const contentHTML = `
        <div style="font-family: Arial, sans-serif; padding: 40px; color: #333;">
          <h1 style="text-align: center; color: #2563eb; font-size: 24px; margin-bottom: 20px;">Flashcards Study Guide</h1>
          <p style="text-align: center; color: #666; font-size: 14px; margin-bottom: 30px;">Generated by SmartStudy AI</p>
          <hr style="border: 1px solid #eee; margin-bottom: 30px;" />

          ${flashcards.map((card, index) => `
            <div style="margin-bottom: 25px; padding-bottom: 15px; border-bottom: 1px solid #f0f0f0; break-inside: avoid;">
              <div style="margin-bottom: 10px;">
                <span style="color: #2563eb; font-weight: bold; font-size: 12px; text-transform: uppercase;">Question ${index + 1}</span>
                <p style="margin: 5px 0; font-size: 16px; font-weight: bold; color: #000;">${card.front}</p>
              </div>
              <div>
                <span style="color: #16a34a; font-weight: bold; font-size: 12px; text-transform: uppercase;">Answer</span>
                <p style="margin: 5px 0; font-size: 14px; line-height: 1.5; color: #444;">${card.back}</p>
              </div>
            </div>
          `).join('')}
        </div>
      `;

      element.innerHTML = contentHTML;

      // 3. Generate PDF from this clean element
            const opt: any = {
              margin:       0.5,
              filename:     'SmartStudy-Flashcards.pdf',
              image:        { type: 'jpeg' as const, quality: 0.98 },
              html2canvas:  { scale: 2 },
              jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
            };

      await html2pdf().set(opt).from(element).save();

    } catch (error) {
      console.error("PDF Generation failed", error);
      alert("Could not generate PDF. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-12 animate-in fade-in slide-in-from-bottom-4">
      
      {/* Header */}
      <div className="text-center mb-10">
        <div className="inline-flex items-center justify-center w-12 h-12 bg-blue-600 rounded-xl text-white shadow-lg mb-6">
          <Layers size={24} />
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-3">Flashcards</h1>
        <p className="text-gray-500 text-lg">Click on each card to reveal the answer</p>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-4 mb-8">
        <button onClick={onBack} className="flex items-center gap-2 text-gray-600 hover:bg-blue-100 hover:text-blue-700 rounded-3xl px-3 py-2   font-medium transition-colors">
          <ArrowLeft size={18} /> Back to Upload
        </button>

        <div className="flex items-center gap-3">
          <button onClick={handleShuffle} className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 font-medium transition-colors">
            <Shuffle size={16} /> Shuffle
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 font-medium transition-colors">
            <RefreshCw size={16} /> Regenerate
          </button>
          
          <button 
             onClick={handleDownloadPDF}
             disabled={isDownloading}
             className="flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 border border-blue-100 rounded-lg hover:bg-blue-100 font-medium transition-colors"
          >
             {isDownloading ? <Loader2 className="animate-spin" size={16}/> : <Download size={16} />} 
             {isDownloading ? "Saving..." : "Download PDF"}
          </button>
        </div>
      </div>

      <div className="text-center text-sm text-gray-400 mb-6">{flashcards.length} flashcards generated</div>

      {/* FLASHCARD GRID */}
      {/* Note: No ref needed here anymore, this is purely for display */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-4">
        {flashcards.map((card, index) => {
          const isFlipped = flippedIndices.includes(index);

          return (
            <div 
              key={index}
              onClick={() => handleCardClick(index)}
              className="h-64 cursor-pointer group perspective-1000"
            >
              <div className={`relative w-full h-full duration-500 preserve-3d transition-transform ${isFlipped ? 'rotate-y-180' : ''}`}>
                
                {/* --- FRONT --- */}
                <div 
                  className="absolute w-full h-full backface-hidden rounded-2xl p-8 flex flex-col items-center justify-center text-center"
                  style={{ 
                    background: 'linear-gradient(135deg, #3b82f6, #4f46e5)', 
                    color: '#ffffff',
                    border: '1px solid #60a5fa',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
                  }}
                >
                  <span className="text-xs font-bold uppercase tracking-widest mb-4 opacity-80" style={{ color: '#dbeafe' }}>Question</span>
                  <h3 className="text-xl font-bold leading-relaxed">{card.front}</h3>
                  <div className="mt-auto pt-4 text-xs opacity-60" style={{ color: '#bfdbfe' }}>Click to flip</div>
                </div>

                {/* --- BACK --- */}
                <div 
                  className="absolute w-full h-full backface-hidden rotate-y-180 rounded-2xl p-8 flex flex-col items-center justify-center text-center shadow-lg"
                  style={{
                    backgroundColor: '#ffffff',
                    border: '2px solid #4ade80',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
                  }}
                >
                  <span className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: '#16a34a' }}>Answer</span>
                  <p className="text-lg font-medium leading-relaxed" style={{ color: '#1f2937' }}>{card.back}</p>
                  <div className="mt-auto pt-4 text-xs" style={{ color: '#9ca3af' }}>Click to flip back</div>
                </div>

              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default FlashcardView;